[build]
  command = "npm run build"
  publish = "build"
  environment = { SECRETS_SCAN_OMIT_KEYS = "REACT_APP_SUPABASE_ANON_KEY,REACT_APP_SUPABASE_URL" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200